### ISSUE TITLE
K2: Lithiumscrap not recyclable?

### ISSUE THREAD

**Issue by Flagran** [Yokmp/Ingredient_Scrap#2]
Hi Yokmp,

I encountered a problem with the lithium scrap. In my Krastorio 2 game there is no possibility to recycle it because the researchable recipe is displayed in the electric melting furnace, but it cannot do anything with HCL and mineral water. I think it was planned to do this in a chemical factory, but the recipe is not displayed there.

Can you take a look about this Problem?!

If you need some Pic´s or my savegame pm me.

Greetings 

Flag

**Comment by Yokmp** [comment]
I'll look into it

**Comment by Yokmp** [comment]
Fixed.
